### ISSUE TITLE
Minor: HTML class name conventions

### ISSUE THREAD

**Issue by Rodrigap** [nellymull/tea-cozy#3]
https://github.com/nellymull/tea-cozy/blob/853da207cdbe5b161cac4bfde5251b52514043ad/resources/css/style.css#L126

This is just a tiny comment, but typically, HTML classes aren't written in camel case, they're hyphenated. Instead of "headLocation", try "head-location"

**Comment by nellymull** [comment]
Awesome! I'm glad you told me, I just started my new project and I had one of these :)
